# Generated by Django 3.2.7 on 2021-09-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Childdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.IntegerField(verbose_name='Sno')),
                ('Child_Name', models.CharField(max_length=30, verbose_name='Child_Name')),
                ('Child_UIDNo', models.IntegerField(verbose_name='Child_UIDNo')),
                ('Gender', models.CharField(max_length=30, verbose_name='Gender')),
                ('Mother_Name', models.CharField(max_length=30, verbose_name='Mother_Name')),
                ('Mother_UIDNo', models.IntegerField(verbose_name='Mother_UIDNo')),
                ('Father_Name', models.CharField(max_length=30, verbose_name='Father_Name')),
                ('Father_UIDNo', models.IntegerField(verbose_name='Father_UIDNo')),
                ('Ration_CardNo', models.IntegerField(verbose_name='Ration_CardNo')),
                ('Mobile_No', models.IntegerField(verbose_name='Mobile_No')),
            ],
        ),
    ]
